{
  parserClass="com.github.michaellazar.gemini_plugin.parser.GeminiParser"

  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

  psiClassPrefix="Gemini"
  psiImplClassSuffix="Impl"
  psiPackage="com.github.michaellazar.gemini_plugin.psi"
  psiImplPackage="com.github.michaellazar.gemini_plugin.psi.impl"

  elementTypeHolderClass="com.github.michaellazar.gemini_plugin.psi.GeminiTypes"
  elementTypeClass="com.github.michaellazar.gemini_plugin.psi.GeminiElementType"
  tokenTypeClass="com.github.michaellazar.gemini_plugin.psi.GeminiTokenType"
}

geminiFile ::= line*

line ::= (h3|h2|h1|quote|ulist|link|pre|plaintext)

h1 ::= H1_HEADER H1_TEXT?
h2 ::= H2_HEADER H2_TEXT?
h3 ::= H3_HEADER H3_TEXT?
quote ::= QUOTE_HEADER QUOTE_TEXT?
ulist ::= ULIST_HEADER ULIST_TEXT?
link ::= LINK_HEADER LINK_URL LINK_TEXT?
pre ::= PRE_HEADER PRE_ALT? PRE_TEXT* PRE_FOOTER?
plaintext ::= PLAIN_HEADER PLAIN_TEXT?